version: "2.18.0"
services:
  github_action_run:
    build: ./
    image: github_action
    stdin_open: true
    tty: true
    privileged: true
    pid: 'host'
    command: [ '/bin/bash' ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "../../:/root/"
