name: cache workflow
on:
  push:
    branches: ["main"]

jobs:
  cache-apt-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Restore Image Cache if it exists
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/ci/cache/docker/my
          key: cache-docker-image

      - name: Update Image Cache if cache miss
        if: steps.cache-docker.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/my-docker
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          /usr/local/bin/docker-compose version
          /usr/local/bin/docker-compose build
          mkdir -p ${{github.workspace}}/ci/cache/docker/my/
          docker image save github_action:1.0 --output ${{github.workspace}}/ci/cache/docker/my/github_action.tar

      - name: Use Image Cache if cache hit
        working-directory: ${{github.workspace}}/
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker image load --input ./ci/cache/docker/my/github_action.tar

      - name: Start containers
        working-directory: ${{github.workspace}}/my-docker
        run: docker compose up -d
