name: workflow-release
on:
  release:
    branches: ["master", "main"]
    types:
      - created

# https://github.com/actions/github-script/blob/1f16022c7518aad314c43abcd029895291be0f52/dist/index.js#L2697
# https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Prepare asserts
        run: |
          mkdir -p ${{github.workspace}}/build
          touch ${{github.workspace}}/build/comment_id.txt
          touch ${{github.workspace}}/build/log.txt
          tar -cvf ${{github.workspace}}/build/asserts.tar ${{github.workspace}}/build/*

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ${{github.workspace}}/build/asserts.tar
